package models

import (
	"github.com/haditssoft/haditssoft-backend/internal/shared/database"
)

func GetSanad(kitab, number string) ([]map[string]interface{}, error) {
	// row := new(MainData)
	rows := make([]map[string]interface{}, 0)
	err := database.DB.Select(
		kitab+".NoHdt", kitab+".NoUrut",
		"DaftarRawi.KodeRawi as KodeRawiA",
		"DaftarRawiB.KodeRawi as KodeRawiB",
		"DaftarRawiC.KodeRawi as KodeRawiC",
		"DaftarRawiD.KodeRawi as KodeRawiD",
		"DaftarRawiE.KodeRawi as KodeRawiE",
		"DaftarRawiF.KodeRawi as KodeRawiF",
		"DaftarRawiG.KodeRawi as KodeRawiG",
		"DaftarRawiH.KodeRawi as KodeRawiH",
		"DaftarRawiI.KodeRawi as KodeRawiI",
		"DaftarRawiJ.KodeRawi as KodeRawiJ",
		"DaftarRawi.Nama as NamaA",
		"DaftarRawiB.Nama as NamaB",
		"DaftarRawiC.Nama as NamaC",
		"DaftarRawiD.Nama as NamaD",
		"DaftarRawiE.Nama as NamaE",
		"DaftarRawiF.Nama as NamaF",
		"DaftarRawiG.Nama as NamaG",
		"DaftarRawiH.Nama as NamaH",
		"DaftarRawiI.Nama as NamaI",
		"DaftarRawiJ.Nama as NamaJ",
		"DaftarRawi.Quality as QualityA",
		"DaftarRawiB.Quality as QualityB",
		"DaftarRawiC.Quality as QualityC",
		"DaftarRawiD.Quality as QualityD",
		"DaftarRawiE.Quality as QualityE",
		"DaftarRawiF.Quality as QualityF",
		"DaftarRawiG.Quality as QualityG",
		"DaftarRawiH.Quality as QualityH",
		"DaftarRawiI.Quality as QualityI",
		"DaftarRawiJ.Quality as QualityJ",
		"DaftarRawi.Kalangan as KalanganA",
		"DaftarRawiB.Kalangan as KalanganB",
		"DaftarRawiC.Kalangan as KalanganC",
		"DaftarRawiD.Kalangan as KalanganD",
		"DaftarRawiE.Kalangan as KalanganE",
		"DaftarRawiF.Kalangan as KalanganF",
		"DaftarRawiG.Kalangan as KalanganG",
		"DaftarRawiH.Kalangan as KalanganH",
		"DaftarRawiI.Kalangan as KalanganI",
		"DaftarRawiJ.Kalangan as KalanganJ",
		"DaftarRawi.Nasab as NasabA",
		"DaftarRawiB.Nasab as NasabB",
		"DaftarRawiC.Nasab as NasabC",
		"DaftarRawiD.Nasab as NasabD",
		"DaftarRawiE.Nasab as NasabE",
		"DaftarRawiF.Nasab as NasabF",
		"DaftarRawiG.Nasab as NasabG",
		"DaftarRawiH.Nasab as NasabH",
		"DaftarRawiI.Nasab as NasabI",
		"DaftarRawiJ.Nasab as NasabJ",
		"DaftarRawi.Kuniyah as KuniyahA",
		"DaftarRawiB.Kuniyah as KuniyahB",
		"DaftarRawiC.Kuniyah as KuniyahC",
		"DaftarRawiD.Kuniyah as KuniyahD",
		"DaftarRawiE.Kuniyah as KuniyahE",
		"DaftarRawiF.Kuniyah as KuniyahF",
		"DaftarRawiG.Kuniyah as KuniyahG",
		"DaftarRawiH.Kuniyah as KuniyahH",
		"DaftarRawiI.Kuniyah as KuniyahI",
		"DaftarRawiJ.Kuniyah as KuniyahJ",
		"DaftarRawi.Laqob as LaqobA",
		"DaftarRawiB.Laqob as LaqobB",
		"DaftarRawiC.Laqob as LaqobC",
		"DaftarRawiD.Laqob as LaqobD",
		"DaftarRawiE.Laqob as LaqobE",
		"DaftarRawiF.Laqob as LaqobF",
		"DaftarRawiG.Laqob as LaqobG",
		"DaftarRawiH.Laqob as LaqobH",
		"DaftarRawiI.Laqob as LaqobI",
		"DaftarRawiJ.Laqob as LaqobJ",
		"DaftarRawi.NegeriHidup as NegeriHidupA",
		"DaftarRawiB.NegeriHidup as NegeriHidupB",
		"DaftarRawiC.NegeriHidup as NegeriHidupC",
		"DaftarRawiD.NegeriHidup as NegeriHidupD",
		"DaftarRawiE.NegeriHidup as NegeriHidupE",
		"DaftarRawiF.NegeriHidup as NegeriHidupF",
		"DaftarRawiG.NegeriHidup as NegeriHidupG",
		"DaftarRawiH.NegeriHidup as NegeriHidupH",
		"DaftarRawiI.NegeriHidup as NegeriHidupI",
		"DaftarRawiJ.NegeriHidup as NegeriHidupJ",
		"DaftarRawi.NegeriWafat as NegeriWafatA",
		"DaftarRawiB.NegeriWafat as NegeriWafatB",
		"DaftarRawiC.NegeriWafat as NegeriWafatC",
		"DaftarRawiD.NegeriWafat as NegeriWafatD",
		"DaftarRawiE.NegeriWafat as NegeriWafatE",
		"DaftarRawiF.NegeriWafat as NegeriWafatF",
		"DaftarRawiG.NegeriWafat as NegeriWafatG",
		"DaftarRawiH.NegeriWafat as NegeriWafatH",
		"DaftarRawiI.NegeriWafat as NegeriWafatI",
		"DaftarRawiJ.NegeriWafat as NegeriWafatJ",
		"DaftarRawi.TahunWafat as TahunWafatA",
		"DaftarRawiB.TahunWafat as TahunWafatB",
		"DaftarRawiC.TahunWafat as TahunWafatC",
		"DaftarRawiD.TahunWafat as TahunWafatD",
		"DaftarRawiE.TahunWafat as TahunWafatE",
		"DaftarRawiF.TahunWafat as TahunWafatF",
		"DaftarRawiG.TahunWafat as TahunWafatG",
		"DaftarRawiH.TahunWafat as TahunWafatH",
		"DaftarRawiI.TahunWafat as TahunWafatI",
		"DaftarRawiJ.TahunWafat as TahunWafatJ",
		"DaftarRawi.RBukhari as RBukhariA",
		"DaftarRawiB.RBukhari as RBukhariB",
		"DaftarRawiC.RBukhari as RBukhariC",
		"DaftarRawiD.RBukhari as RBukhariD",
		"DaftarRawiE.RBukhari as RBukhariE",
		"DaftarRawiF.RBukhari as RBukhariF",
		"DaftarRawiG.RBukhari as RBukhariG",
		"DaftarRawiH.RBukhari as RBukhariH",
		"DaftarRawiI.RBukhari as RBukhariI",
		"DaftarRawiJ.RBukhari as RBukhariJ",
		"DaftarRawi.RMuslim as RMuslimA",
		"DaftarRawiB.RMuslim as RMuslimB",
		"DaftarRawiC.RMuslim as RMuslimC",
		"DaftarRawiD.RMuslim as RMuslimD",
		"DaftarRawiE.RMuslim as RMuslimE",
		"DaftarRawiF.RMuslim as RMuslimF",
		"DaftarRawiG.RMuslim as RMuslimG",
		"DaftarRawiH.RMuslim as RMuslimH",
		"DaftarRawiI.RMuslim as RMuslimI",
		"DaftarRawiJ.RMuslim as RMuslimJ",
		"DaftarRawi.RAbuDaud as RAbuDaudA",
		"DaftarRawiB.RAbuDaud as RAbuDaudB",
		"DaftarRawiC.RAbuDaud as RAbuDaudC",
		"DaftarRawiD.RAbuDaud as RAbuDaudD",
		"DaftarRawiE.RAbuDaud as RAbuDaudE",
		"DaftarRawiF.RAbuDaud as RAbuDaudF",
		"DaftarRawiG.RAbuDaud as RAbuDaudG",
		"DaftarRawiH.RAbuDaud as RAbuDaudH",
		"DaftarRawiI.RAbuDaud as RAbuDaudI",
		"DaftarRawiJ.RAbuDaud as RAbuDaudJ",
		"DaftarRawi.RTirmidzi as RTirmidziA",
		"DaftarRawiB.RTirmidzi as RTirmidziB",
		"DaftarRawiC.RTirmidzi as RTirmidziC",
		"DaftarRawiD.RTirmidzi as RTirmidziD",
		"DaftarRawiE.RTirmidzi as RTirmidziE",
		"DaftarRawiF.RTirmidzi as RTirmidziF",
		"DaftarRawiG.RTirmidzi as RTirmidziG",
		"DaftarRawiH.RTirmidzi as RTirmidziH",
		"DaftarRawiI.RTirmidzi as RTirmidziI",
		"DaftarRawiJ.RTirmidzi as RTirmidziJ",
		"DaftarRawi.RNasai as RNasaiA",
		"DaftarRawiB.RNasai as RNasaiB",
		"DaftarRawiC.RNasai as RNasaiC",
		"DaftarRawiD.RNasai as RNasaiD",
		"DaftarRawiE.RNasai as RNasaiE",
		"DaftarRawiF.RNasai as RNasaiF",
		"DaftarRawiG.RNasai as RNasaiG",
		"DaftarRawiH.RNasai as RNasaiH",
		"DaftarRawiI.RNasai as RNasaiI",
		"DaftarRawiJ.RNasai as RNasaiJ",
		"DaftarRawi.RIbnuMajah as RIbnuMajahA",
		"DaftarRawiB.RIbnuMajah as RIbnuMajahB",
		"DaftarRawiC.RIbnuMajah as RIbnuMajahC",
		"DaftarRawiD.RIbnuMajah as RIbnuMajahD",
		"DaftarRawiE.RIbnuMajah as RIbnuMajahE",
		"DaftarRawiF.RIbnuMajah as RIbnuMajahF",
		"DaftarRawiG.RIbnuMajah as RIbnuMajahG",
		"DaftarRawiH.RIbnuMajah as RIbnuMajahH",
		"DaftarRawiI.RIbnuMajah as RIbnuMajahI",
		"DaftarRawiJ.RIbnuMajah as RIbnuMajahJ",
		"DaftarRawi.RAhmad as RAhmadA",
		"DaftarRawiB.RAhmad as RAhmadB",
		"DaftarRawiC.RAhmad as RAhmadC",
		"DaftarRawiD.RAhmad as RAhmadD",
		"DaftarRawiE.RAhmad as RAhmadE",
		"DaftarRawiF.RAhmad as RAhmadF",
		"DaftarRawiG.RAhmad as RAhmadG",
		"DaftarRawiH.RAhmad as RAhmadH",
		"DaftarRawiI.RAhmad as RAhmadI",
		"DaftarRawiJ.RAhmad as RAhmadJ",
		"DaftarRawi.RMalik as RMalikA",
		"DaftarRawiB.RMalik as RMalikB",
		"DaftarRawiC.RMalik as RMalikC",
		"DaftarRawiD.RMalik as RMalikD",
		"DaftarRawiE.RMalik as RMalikE",
		"DaftarRawiF.RMalik as RMalikF",
		"DaftarRawiG.RMalik as RMalikG",
		"DaftarRawiH.RMalik as RMalikH",
		"DaftarRawiI.RMalik as RMalikI",
		"DaftarRawiJ.RMalik as RMalikJ",
		"DaftarRawi.RDarimi as RDarimiA",
		"DaftarRawiB.RDarimi as RDarimiB",
		"DaftarRawiC.RDarimi as RDarimiC",
		"DaftarRawiD.RDarimi as RDarimiD",
		"DaftarRawiE.RDarimi as RDarimiE",
		"DaftarRawiF.RDarimi as RDarimiF",
		"DaftarRawiG.RDarimi as RDarimiG",
		"DaftarRawiH.RDarimi as RDarimiH",
		"DaftarRawiI.RDarimi as RDarimiI",
		"DaftarRawiJ.RDarimi as RDarimiJ",
	).Table(
		kitab,
	).Joins(
		"INNER JOIN DaftarRawi ON "+kitab+".J1 = DaftarRawi.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiB ON "+kitab+".J2 = DaftarRawiB.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiC ON "+kitab+".J3 = DaftarRawiC.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiD ON "+kitab+".J4 = DaftarRawiD.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiE ON "+kitab+".J5 = DaftarRawiE.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiF ON "+kitab+".J6 = DaftarRawiF.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiG ON "+kitab+".J7 = DaftarRawiG.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiH ON "+kitab+".J8 = DaftarRawiH.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiI ON "+kitab+".J9 = DaftarRawiI.KodeRawi",
	).Joins(
		"INNER JOIN DaftarRawi as DaftarRawiJ ON "+kitab+".J10 = DaftarRawiJ.KodeRawi",
	).Where(
		kitab+".NoHdt = ?", number,
	).Order(
		kitab + ".NoUrut ASC",
	).Find(&rows).Error
	if err != nil {
		return nil, err
	}

	return rows, nil
}
